version: "3"
services:
 mongo-pinner:
  image: mongo:4.2.5
  container_name: mongo-pinner
  ports:
   - "27019:27017"
  environment:
    MONGO_INITDB_DATABASE: pinner
  volumes:
   - ../pinner/resources/mongodb:/docker-entrypoint-initdb.d

 pinner:
  build: ../pinner
  container_name: pinner
  ports:
    - "8082:8082"
  environment:
    MONGO_HOST: localhost
    MONGO_PORT: 27019
    ROOM_HOST: localhost
    ROOM_PORT: 8081
    FLASK_PORT: 8082
  depends_on:
    - mongo-pinner
    - room
  network_mode: host

 mongo-room:
  image: mongo:4.2.5
  container_name: mongo-room
  ports:
   - "27017:27017"
  environment:
    MONGO_INITDB_DATABASE: room
  volumes:
   - ../room/resources/mongodb:/docker-entrypoint-initdb.d

 room:
  build: ../room
  container_name: room
  ports:
    - "8081:8081"
  environment:
    MONGO_HOST: localhost
    MONGO_PORT: 27017
    CHAT_HOST: localhost
    CHAT_PORT: 8080
    FLASK_PORT: 8081
  depends_on:
    - mongo-room
    - chat
  network_mode: host

 mongo-chat:
  image: mongo:4.2.5
  container_name: mongo-chat
  ports:
   - "27018:27017"
  environment:
    MONGO_INITDB_DATABASE: chat
  volumes:
   - ../chat/resources/mongodb:/docker-entrypoint-initdb.d 

 chat:
  build: ../chat
  container_name: chat
  ports:
    - "8080:8080"
  environment:
    MONGO_HOST: localhost
    MONGO_PORT: 27018
    FLASK_PORT: 8080
  depends_on:
    - mongo-chat
  network_mode: host